### ISSUE TITLE
matmul CUDA example fails to compile

### ISSUE THREAD

**Issue by hmparanjape** [ContinuumIO/numbapro-examples#7]
I am trying to run the [matmul.py](https://github.com/ContinuumIO/numbapro-examples/blob/master/cudajit/matmul.py) example on Ubuntu 12.04LTS. For this, I have installed NumbaPro by following the instructions on [continuum.io Accelerate page](https://store.continuum.io/static/img/AnacondaAccelerate-Quickstart.pdf).  
```
conda update conda
conda install accelerate
```

On running the program, I get an error -  
```
software-dev@ubuntu:~$ python numbaprotest.py 
Traceback (most recent call last):
  File "numbaprotest.py", line 12, in <module>
    @cuda.jit(argtypes=[f4[:,:], f4[:,:], f4[:,:]])
  File "/home/software-dev/miniconda/lib/python2.7/site-packages/numba/cuda/decorators.py", line 91, in kernel_jit
    kernel.bind()
  File "/home/software-dev/miniconda/lib/python2.7/site-packages/numba/cuda/compiler.py", line 321, in bind
    self._func.get()
  File "/home/software-dev/miniconda/lib/python2.7/site-packages/numba/cuda/compiler.py", line 256, in get
    ptx = self.ptx.get()
  File "/home/software-dev/miniconda/lib/python2.7/site-packages/numba/cuda/compiler.py", line 228, in get
    **self._extra_options)
  File "/home/software-dev/miniconda/lib/python2.7/site-packages/numba/cuda/cudadrv/nvvm.py", line 422, in llvm_to_ptx
    ptx = cu.compile(**opts)
  File "/home/software-dev/miniconda/lib/python2.7/site-packages/numba/cuda/cudadrv/nvvm.py", line 213, in compile
    self._try_error(err, 'Failed to compile\n')
  File "/home/software-dev/miniconda/lib/python2.7/site-packages/numba/cuda/cudadrv/nvvm.py", line 231, in _try_error
    self.driver.check_error(err, "%s\n%s" % (msg, self.get_log()))
  File "/home/software-dev/miniconda/lib/python2.7/site-packages/numba/cuda/cudadrv/nvvm.py", line 120, in check_error
    raise exc
numba.cuda.cudadrv.error.NvvmError: Failed to compile

<unnamed> (767, 45): parse error: expected top-level entity
NVVM_ERROR_COMPILATION
```

I resolved this issue by following the advice on [Anaconda Google Group](https://groups.google.com/a/continuum.io/forum/#!topic/anaconda/cRI3Sqj4mZA). I upgraded cudatoolkit to v 7.0-1

After this, I get a new error -  
```
software-dev@ubuntu:~$ python numbaprotest.py 
Traceback (most recent call last):
  File "numbaprotest.py", line 12, in <module>
    @cuda.jit(argtypes=[f4[:,:], f4[:,:], f4[:,:]])
  File "/home/software-dev/miniconda/lib/python2.7/site-packages/numba/cuda/decorators.py", line 91, in kernel_jit
    kernel.bind()
  File "/home/software-dev/miniconda/lib/python2.7/site-packages/numba/cuda/compiler.py", line 321, in bind
    self._func.get()
  File "/home/software-dev/miniconda/lib/python2.7/site-packages/numba/cuda/compiler.py", line 260, in get
    linker.add_ptx(ptx)
  File "/home/software-dev/miniconda/lib/python2.7/site-packages/numba/cuda/cudadrv/driver.py", line 1186, in add_ptx
    raise LinkerError("%s\n%s" % (e, self.error_log))
numba.cuda.cudadrv.driver.LinkerError: Call to cuLinkAddData results in CUDA_ERROR_NO_BINARY_FOR_GPU
ptxas application ptx input, line 9; error   : Unsupported .version 4.2; current version is '3.2'
ptxas fatal   : Ptx assembly aborted due to errors
```

Is there a resolution for this?

Thanks.

**Comment by hmparanjape** [comment]
FYI, output from `numbapro.check_cuda()` is as follows:  
```
>>> numbapro.check_cuda()
------------------------------libraries detection-------------------------------
Finding cublas
	located at /home/software-dev/miniconda/lib/libcublas.so.7.0.28
	trying to open library...	ok
Finding cusparse
	located at /home/software-dev/miniconda/lib/libcusparse.so.7.0.28
	trying to open library...	ok
Finding cufft
	located at /home/software-dev/miniconda/lib/libcufft.so.7.0.35
	trying to open library...	ok
Finding curand
	located at /home/software-dev/miniconda/lib/libcurand.so.7.0.28
	trying to open library...	ok
Finding nvvm
	located at /home/software-dev/miniconda/lib/libnvvm.so.3.0.0
	trying to open library...	ok
	finding libdevice for compute_20...	ok
	finding libdevice for compute_30...	ok
	finding libdevice for compute_35...	ok
-------------------------------hardware detection-------------------------------
Found 1 CUDA devices
id 0            Quadro K4000                              [SUPPORTED]
                      compute capability: 3.0
                           pci device id: 0
                              pci bus id: 5
Summary:
	1/1 devices are supported
PASSED
True
```

**Comment by sklam** [comment]
The LinkerError is indicating that a newer Nvidia driver is required.  The new version of numbapro generates PTX of version 4.2 but your driver is expecting version 3.2.  Since the driver is non-redistributable, you will need to get it from Nvidia directly.

**Comment by hmparanjape** [comment]
Thanks for the tip.

I will try to install the latest driver.
